### PR TITLE
Support patterns in dependencies' artifacts

### PR DESCRIPTION
**Pull request by nskvortsov**
Added a processor `DependenciesRegexProcessor` that will list artifacts from teamcity-ivy.xml files and  match them with required artifacts names. The implementation requires customized Ivy Resolver due to [this issue](https://discuss.gradle.org/t/artifactresolutionquery-does-not-use-ivy-repository-pattern/10788).

Addional refactorings:
- _teamcityServer_ is now an extension in _repositories_ scope
- `pin` configuratoin moved to TeamCity Ivy repository entity
- `PluginConfiguration` replaced with `PinConfiguratoin` (available via `project.pinConifig`)
- `RepositoryBuilder` is no longer used,
- `AritfactDescriptor` has no need to split path and artifact name
- Http auth support (during artifact download)

### CODE REVIEW

**Comment by jk1** [comment]
Looks like some test are failing: https://travis-ci.org/jk1/TeamCity-dependencies-gradle-plugin/builds/73164262

**Comment by nskvortsov** [comment]
I'm not sure how did "Canonical" interfered with "EqualsAndHashcode", but removing latter fixed the spec: https://travis-ci.org/jk1/TeamCity-dependencies-gradle-plugin/builds/73884876

**Comment by jk1** [comment]
Thanks a lot. I did some tests and it looks nothing is broken after all. There are some minor style issues I'd rather fix in place though.

**Comment by nskvortsov** [comment]
Could you please perform a release to `plugins.gradle.org`?

**Pull request merged**
